# BL40A2010 Introduction to IoT-Based Systems

## Example for HW 6, 12.10.2018

### Author: Pedro Nardelli

**(1) Consider the game whose payoff table is presented below. What is the relation between the payoffs values $x$, $y$, $w$ and $z$ so that the game can be classified as *Dove and Hawk*?**

|                | $B$ aggressive  | $B$ not-aggressive     |
|----------------|:---------------:|--------------:|
| $A$ agreessive |  $A \rightarrow x$   | $A \rightarrow w$  |
|                |  $B \rightarrow x$   | $B\rightarrow y$  |
|                |                 |               |
| $A$ not-aggressive |  $A\rightarrow y$      | $A\rightarrow z$  |
|                |  $B\rightarrow w$   | $B\rightarrow z$  |


**Verify the analytical results with numerical examples using [nashpy](https://nashpy.readthedocs.io/en/stable/index.html).**

*Answer:* To be a Dove and Hawk game:
- Both being aggressive is worse than both being timid, therefore:  x < z,
- Being aggressive gives advantage in relation to be timid: w > y,
- There shall be Nash equilibria when one player is aggressive and the other is timid. In this sense: w > z and  y > x . 

Putting all together:  x < y < z < w 

In [ ]:
#Verification with nashpy
#Installing a missing library
! pip install nashpy

In [ ]:
import numpy as np
import nashpy as nash

### Test 1:  x < y < z < w 


|                | $B$ aggressive  | $B$ not-aggressive     |
|----------------|:---------------:|--------------:|
| $A$ agreessive |  $A \rightarrow x$   | $A \rightarrow w$  |
|                |  $B \rightarrow x$   | $B\rightarrow y$  |
|                |                 |               |
| $A$ not-aggressive |  $A\rightarrow y$      | $A\rightarrow z$  |
|                |  $B\rightarrow w$   | $B\rightarrow z$  |


$$
A =
\begin{pmatrix}
    x & w\\
    y & z
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    x & y\\
    w & z
\end{pmatrix}
$$

### Test 1:  x < y < z < w 


|                | $B$ aggressive  | $B$ not-aggressive     |
|----------------|:---------------:|--------------:|
| $A$ agreessive |  $A \rightarrow 0$   | $A \rightarrow 5$  |
|                |  $B \rightarrow 0$   | $B\rightarrow 1$  |
|                |                 |               |
| $A$ not-aggressive |  $A\rightarrow 1$      | $A\rightarrow 4$  |
|                |  $B\rightarrow 5$   | $B\rightarrow 4$  |


$$
A =
\begin{pmatrix}
    0 & 5\\
    1 & 4
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    0 & 1\\
    5 & 4
\end{pmatrix}
$$

In [ ]:
x = 0
y = 1 
z = 4
w = 5
p=(z-w)/(x+z-y-w) 
p

0.5

In [ ]:
# Test 1 
A = [[x, w], [y, z]]
B = [[x, y], [w, z]]
hawk_dove = nash.Game(A, B)
hawk_dove

Bi matrix game with payoff matrices:

Row player:
[[0 5]
 [1 4]]

Column player:
[[0 1]
 [5 4]]

In [ ]:
eqs = hawk_dove.support_enumeration()
list(eqs)

[(array([1., 0.]), array([0., 1.])),
 (array([0., 1.]), array([1., 0.])),
 (array([0.5, 0.5]), array([0.5, 0.5]))]

This output gives the *mixed strategies Nash equilibria.*

- **First line:** Player A (first array) will be aggressive with probability $1$ and be timid with probability $0$; Player B (second array) will be aggressive with probability $0$ and be timid with probability $1$. 
- **Second line:** Player A (first array) will be aggressive with probability $0$ and be timid with probability $1$; Player B (second array) will be aggressive with probability $1$ and be timid with probability $0$. 

This satisfies the condition of being a Dove and Hawk game. Note that there is also a third Nash equilibrium, but a mixed strategy one.
- **Third line:** Player A (first array) will be aggressive with probability $3/4$ and be timid with probability $1/4$; Player B (second array) will be aggressive with probability $3/4$ and be timid with probability $1/4$. Check it out by hand.

### Test 2: z > w


|                | $B$ aggressive  | $B$ not-aggressive     |
|----------------|:---------------:|--------------:|
| $A$ agreessive |  $A \rightarrow 0$   | $A \rightarrow 2$  |
|                |  $B \rightarrow 0$   | $B\rightarrow 1$  |
|                |                 |               |
| $A$ not-aggressive |  $A\rightarrow 1$      | $A\rightarrow 3$  |
|                |  $B\rightarrow 2$   | $B\rightarrow 3$  |

$$
A =
\begin{pmatrix}
    0 & 2\\
    1 & 3
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    0 & 1\\
    2 & 3
\end{pmatrix}
$$

In [ ]:
# Test 2 -> x=0, y=1, z=3 and w=2
A = [[0, 2], [1, 3]]
B = [[0, 1], [2, 3]]
hawk_dove2 = nash.Game(A, B)
hawk_dove2

Bi matrix game with payoff matrices:

Row player:
[[0 2]
 [1 3]]

Column player:
[[0 1]
 [2 3]]

In [ ]:
eqs = hawk_dove2.support_enumeration()
list(eqs)

[(array([0., 1.]), array([0., 1.]))]

This indicates a unique Nash equilibrium (domiant strategy) of both being timid

**(2) Justify why the game from the previous exercise is or is not a sound model when $A$ and $B$ are:**

**1. Two countries developing defense policies.**


**2. Competitive companies in the market discussing standardization.**


**3. Two different autonomous IoT-based home energy management algorithms that are focus on energy efficiency.**


**4. Two different autonomous IoT-based home energy management algorithms that are focus on profit maximization.**

Answer: Dove and Hawk game as a model.

**1.** Yes. For example country A has an aggressive external policy to develop nuclear weapons. Country B may invade the country and cause a nuclear war (bad to all), or being passive (timid) and let the other country develop the weapon without cause war (A is in an advantageous situation and B cannot act without becoming worse off).

**2.** Probably yes if there is a competition between two standards. It may be a good model if we consider: both losing by having two standards. An aggressive company (A) can push its preferable standard and the other (B) being timid; this case has advantages of having only one standard. Nevertheless, the "good" solution would be having the two companies agreeing in a standard without any imposing their positions (both timid).

**3.** No since they can work in cooperation and have the same shared goal. The energy efficiency of house A does not affect the payoff of house B.

**4.** Probably no. But it can also be yes if they are competing for the same resource and decisions of A and B may affect each other.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6e014854-0d33-4882-b3ba-5e4227a689e6' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>