# BL40A2010 Introduction to IoT-Based Systems

## Assignment 6, DD.MM.YYYY

### Author:

**Prisoner's dilemma** is a standard example of a game analyzed in game theory that shows why two completely rational individuals might not cooperate, even if it appears that it is in their best interests to do so. It was originally framed by Merrill Flood and Melvin Dresher while working at RAND in 1950. Albert W. Tucker formalized the game with prison sentence rewards and named it "prisoner's dilemma", presenting it as follows:

"Two members of a criminal gang are arrested and imprisoned. Each prisoner is in solitary confinement with no means of communicating with the other. The prosecutors lack sufficient evidence to convict the pair on the principal charge, but they have enough to convict both on a lesser charge. Simultaneously, the prosecutors offer each prisoner a bargain. Each prisoner is given the opportunity either to betray the other by testifying that the other committed the crime, or to cooperate with the other by remaining silent. The possible outcomes are:

- If A and B each betray the other (not-cooperating to each other), each of them serves $z$ years in prison (payoff of $-z$)
- If A betrays B (not-cooperating with B) but B remains silent (cooperating with A), A will serve $y$ years in prison (payoff $-y$) and B will serve $w$ years  (payoff of $-w$).
- If B betrays A (not-cooperating with A) but A remains silent (cooperating with B), B will serve $y$ years in prison (payoff $-y$) and A will serve $w$ years  (payoff of $-w$).
- If A and B both remain silent, both of them will serve $x$ years in prison (payoff of $-x$)."

The payoff table is presented below. 

|                | $B$ cooperates  | $B$ not-cooperating   |
|----------------|:---------------:|--------------:|
| $A$ cooperates |  $A \rightarrow -x$   | $A\rightarrow -w$  |
|                |  $B\rightarrow -x$   | $B\rightarrow -y$  |
|                |                 |               |
| $A$ not-cooperating   |  $A\rightarrow -y$   | $A\rightarrow -z$  |
|                |  $B\rightarrow -w$   | $B\rightarrow -z$  |

**However, this is only a *Prisoner's Dilemma GAME* for A GIVEN RELATION between the years in prison (payoffs) as to be studied next.**

ps. Text adapted from [Wikipedia](https://en.wikipedia.org/wiki/Prisoner's_dilemma).

**(1) Consider the Prisoner's dilemma description given above.**

**(a) What is the relation between the payoffs values $x\geq 0$, $y\geq 0$, $w\geq 0$ and $z \geq 0$ so that the game can be classified as [Prisoner's Dilemma](https://en.wikipedia.org/wiki/Prisoner's_dilemma)?**

**(b) Verify the results (i.e., the proposed inequality) with numerical examples using [nashpy](https://nashpy.readthedocs.io/en/stable/index.html). Please provide one example when the inequality holds and one it does not (check my example for Dove and Hawyk game).**

a) To be classified as Prisoner's Dilemma, the payoff relationship is such that:
 - Mutual cooperation is superior to mutual defection. ($$x > z$$)
 - Defection is the dominant strategy for both parties. ($$y > x$$ and $$z > w$$)
 
 So to put it together, the relation would be **$$y > x > z > w$$** (meaning y is a better "deal" than x because the prisoner serves less time in prison)

In [ ]:
!pip install nashpy

  Using cached nashpy-0.0.22.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-35guhc0w/nashpy_98c541c3cb65453ca5fdede3025d98b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-35guhc0w/nashpy_98c541c3cb65453ca5fdede3025d98b1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vdq815xd
       cwd: /tmp/pip-install-35guhc0w/nashpy_98c541c3cb65453ca5fdede3025d98b1/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-35guhc0w/nashpy_98c541c3cb65453ca5fdede3025d98b1/setup.py", line 6, 

In [ ]:
import numpy as np
import nashpy as nash

### Test 1: w < z < x < y

|                | $B$ cooperates  | $B$ not-cooperating   |
|----------------|:---------------:|--------------:|
| $A$ cooperates |  $A \rightarrow -x$   | $A\rightarrow -w$  |
|                |  $B\rightarrow -x$   | $B\rightarrow -y$  |
|                |                 |               |
| $A$ not-cooperating   |  $A\rightarrow -y$   | $A\rightarrow -z$  |
|                |  $B\rightarrow -w$   | $B\rightarrow -z$  |

$$
A =
\begin{pmatrix}
    -x & -w\\
    -y & -z
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    -x & -y\\
    -w & -z
\end{pmatrix}
$$

$$
A =
\begin{pmatrix}
    -1 & -3\\
    0 & -2
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    -1 & 0\\
    -3 & -2
\end{pmatrix}
$$

To visualize it better, -1 means the prisoner will serve 1 more year in prison, 0 means the prisoner will be let go, etc.

In [ ]:
x = -1
y = 0 
z = -2
w = -3

In [ ]:
A = np.array([[x, w], [y, z]])
B = np.array([[x, y], [w, z]])
prisoners_dilemma = nash.Game(A, B)
prisoners_dilemma

Bi matrix game with payoff matrices:

Row player:
[[-1 -3]
 [ 0 -2]]

Column player:
[[-1  0]
 [-3 -2]]

In [ ]:
eqs = prisoners_dilemma.support_enumeration()
list(eqs)

[(array([0., 1.]), array([0., 1.]))]

The results above is a Nash equilibrium where both betrays (dominant strategy)

### Test 2: x > y (x better deal than y)

|                | $B$ cooperates  | $B$ not-cooperating   |
|----------------|:---------------:|--------------:|
| $A$ cooperates |  $A \rightarrow 0$   | $A\rightarrow -3$  |
|                |  $B\rightarrow 0$   | $B\rightarrow -1$  |
|                |                 |               |
| $A$ not-cooperating   |  $A\rightarrow -1$   | $A\rightarrow -2$  |
|                |  $B\rightarrow -3$   | $B\rightarrow -2$  |


$$
A =
\begin{pmatrix}
    0 & -3\\
    -1 & -2
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    0 & -1\\
    -3 & -2
\end{pmatrix}
$$
x = 0
y = -1
w = -3
z = -2

In [ ]:
C = [[0, -3], [-1, -2]]
D = [[0, -1], [-3, -2]]
prisoners_dilemma2 = nash.Game(C,D)
prisoners_dilemma2

Bi matrix game with payoff matrices:

Row player:
[[ 0 -3]
 [-1 -2]]

Column player:
[[ 0 -1]
 [-3 -2]]

In [ ]:
eqs2 = prisoners_dilemma2.support_enumeration()
list(eqs2)

[(array([1., 0.]), array([1., 0.])),
 (array([0., 1.]), array([0., 1.])),
 (array([0.5, 0.5]), array([0.5, 0.5]))]

The first two lines output:
- In the first line, Player A (first array) will cooperate with probability $1$ and betrays with probability $0$; Player B (second array) will cooperate with probability $1$ and betrays with probability $0$.
- In the first line, Player A (first array) will cooperate with probability $0$ and betrays with probability $1$; Player B (second array) will cooperate with probability $0$ and betrays with probability $1$.
This satisfies the classification of the Prisoner's Dilemma game, meaning either both will confess or both cooperate. However, there is another Nash equilibrium (mixed strategy) in the third line:
- Player A (first array) will cooperate with probability $1/3$ and betrays with probability $3/4$; Player B (second array) will cooperate with probability $1/3$ and betrays with probability $3/4$.

**(2) Justify why the game from the previous exercise is or is not a good (reasonable) model when $A$ and $B$ are:**

**1. Two trained members from the army when they are in prison.**


**2. Competitive companies in the market discussing standardization.**


**3. Two different autonomous IoT-based home energy management algorithms that are focus on energy efficiency.**


**4. Two different autonomous IoT-based home energy management algorithms that are focus on profit maximization.**

**ps. You need to think about the assumption used in Game Theory and in the Prisoner's dilemma problem setting.**

Answer: \
1. Probably yes, but it could be no if we consider a trained member of an army have loyalty to their armed force and its members, which does not fulfill the required condition for prisoner's dilemma game.
2. No, if we consider standardization of public goods that is used by multiple countries, such as shipping containers and inter-continental train system. Using the prisoner's dilemma model, both companies **would not lose if they're both having different standards**, which is **not applicable** to standardization where having two standards for the same product is highly undesirable.
3. No, because both algorithms can work in cooperation with each other and energy efficiency of house A does not affect the payout of house B.
4. Yes. If the energy management of house A betrays, then A will get a significantly higher profit than B and vice versa. Of course, cooperation between both energy management algorithms is more beneficial than if both algorithms betray against each other, but even if both betray against each other it is still better than if one algorithm cooperate and the other betrays.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6e014854-0d33-4882-b3ba-5e4227a689e6' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>